### ISSUE TITLE
Update for Version 10

### ISSUE THREAD

**Issue by Dave247** [thomasfn/EcoSmartTaxMod#47]
As expected [beta 0.6.1](https://github.com/thomasfn/EcoSmartTaxMod/releases/tag/0.6.1) crashes on startup on version 10 of the server. 

```
[23:18:06.660] [17] [ Warn] [Eco] Failed to get derived types for 'Eco.World.Blocks.Block' in assembly 'EcoSmartTaxMod, Version=0.6.1.0, Culture=neutral, PublicKeyToken=null' (usually safe to ignore for third party assembly). Error message: Unable to load one or more of the requested types.
Attempted to access a missing method.
Attempted to access a missing method.
Attempted to access a missing method.
 
[23:18:06.798] [4] [ Info] [Eco] Server Initialization                             ... Finished in 5.683 sec
 
[23:18:06.798] [24] [Error] [Eco] Failed to start the server. Exception was Exception: ReflectionTypeLoadException
Message:Unable to load one or more of the requested types.
Attempted to access a missing method.
Attempted to access a missing method.
Attempted to access a missing method.
Source:System.Private.CoreLib

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Attempted to access a missing method.
Attempted to access a missing method.
Attempted to access a missing method.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Eco.Shared.Utils.ReflectionCache.<>c.<GetTypesCached>b__10_0(Assembly a)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Eco.Shared.Utils.ReflectionCache.GetTypesCached(Assembly assembly)
   at Eco.Shared.Utils.ReflectionCache.<>c.<GetGameAssembliesTypes>b__21_0(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Eco.Core.Serialization.SimpleSerializer.InitializeSerializableTypes()
   at Eco.Core.Serialization.SimpleSerializer..cctor()
System.MissingMethodException: Attempted to access a missing method.
System.MissingMethodException: Attempted to access a missing method.
System.MissingMethodException: Attempted to access a missing method.
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
One or more errors occurred. (The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.)
The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.
 
[23:18:11.804] [24] [ Info] [Eco] Shutdown finished
 
[23:18:11.804] [24] [Error] [Eco] Errors report:
Failed to get derived types for 'Eco.World.Blocks.Block' in assembly 'EcoSmartTaxMod, Version=0.6.1.0, Culture=neutral, PublicKeyToken=null' (usually safe to ignore for third party assembly). Error message: Unable to load one or more of the requested types.
Attempted to access a missing method.
Attempted to access a missing method.
Attempted to access a missing method.: 1
Failed to start the server. Exception was Exception: ReflectionTypeLoadException
Message:Unable to load one or more of the requested types.
Attempted to access a missing method.
Attempted to access a missing method.
Attempted to access a missing method.
Source:System.Private.CoreLib

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Attempted to access a missing method.
Attempted to access a missing method.
Attempted to access a missing method.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Eco.Shared.Utils.ReflectionCache.<>c.<GetTypesCached>b__10_0(Assembly a)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Eco.Shared.Utils.ReflectionCache.GetTypesCached(Assembly assembly)
   at Eco.Shared.Utils.ReflectionCache.<>c.<GetGameAssembliesTypes>b__21_0(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Eco.Core.Serialization.SimpleSerializer.InitializeSerializableTypes()
   at Eco.Core.Serialization.SimpleSerializer..cctor()
System.MissingMethodException: Attempted to access a missing method.
System.MissingMethodException: Attempted to access a missing method.
System.MissingMethodException: Attempted to access a missing method.
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
One or more errors occurred. (The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.)
The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.
: 1
```

**Comment by thomasfn** [comment]
Fixed in [beta 0.7.0](https://github.com/thomasfn/EcoSmartTaxMod/releases/tag/0.7.0)
