### ISSUE TITLE
Version 10.2.0 crashes client on tax / pay action

### ISSUE THREAD

**Issue by dlehman83** [thomasfn/EcoSmartTaxMod#50]
Hello,
I'm testing the 10.2.0 update and when I take a action that would result in a tax or payment action my client crashes.  

This is what is in the server log.

```
[11:39:16] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Shared.Networking.RPCManager.Invoke(INetClient client, RPCInvocation invocation, Boolean notifyOnPermissionFail)
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodName)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONValue bsonValue)
   at Eco.Plugins.Networking.Client.<.ctor>b__78_4()
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Eco.Shared.Networking.RPCManager.Invoke(INetClient client, RPCInvocation invocation, Boolean notifyOnPermissionFail)
   at Eco.Core.Controller.ControllerManager.HandleViewRPC(INetClient client, Int32 universalID, String methodIdOrName, BSONObject bson)
   at InvokeStub_Client.ViewRPC(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
System.MissingMethodException: Attempted to access a missing method.
   at Eco.Mods.SmartTax.Jurisdiction.FromContext(IContextObject context, Settlement settlement)
   at Eco.Mods.SmartTax.SmartTax_LegalAction.Do(LocString description, IContextObject context, Settlement jurisdictionSettlement)
   at Eco.Mods.SmartTax.SmartTax_LegalAction.Perform(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.LegalAction.PerformAndProcessResult(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, AccountChangeSet acc, LawSection section, Int32 index, LocStringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.LawSection.InternalPerform(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.Law.TryPerform(GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.GetResultWithLock(GameActionPack pack)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User userToNotify, GameActionPack actionPack)
   at Eco.Mods.TechTree.AxeItem.Chop(Player player, InteractionTriggerInfo triggerInfo, InteractionTarget target) in D:\Eco1020Server\Mods\UserCode\Tools\AxeItem.override.cs:line 115
   at InvokeStub_AxeItem.Chop(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Thank you

**Comment by vkomputers** [comment]
I also have a problem in version 10.2
[21:19:41.530] [50] [Error] [Eco] System.MissingMethodException: Attempted to access a missing method.
   at Eco.Mods.SmartTax.Jurisdiction.FromContext(IContextObject context, Settlement settlement)
   at Eco.Mods.SmartTax.SmartPay_LegalAction.Do(LocString description, IContextObject context, Settlement jurisdictionSettlement)
   at Eco.Mods.SmartTax.SmartPay_LegalAction.Perform(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.LegalAction.PerformAndProcessResult(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, AccountChangeSet acc, LawSection section, Int32 index, LocStringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.LawSection.InternalPerform(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.Law.TryPerform(GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.GetResultWithLock(GameActionPack pack)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User userToNotify, GameActionPack actionPack)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, User userToNotify)
   at Eco.Gameplay.Placement.WorldObjectPlacementUtils.TryPlaceWorldObjectNow(Player player, WorldObjectItem item, ItemStack containingStack, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.Place(Player player, Vector3i pos, Quaternion rotation)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() System.MissingMethodException: Attempted to access a missing method.
   at Eco.Mods.SmartTax.Jurisdiction.FromContext(IContextObject context, Settlement settlement)
   at Eco.Mods.SmartTax.SmartPay_LegalAction.Do(LocString description, IContextObject context, Settlement jurisdictionSettlement)
   at Eco.Mods.SmartTax.SmartPay_LegalAction.Perform(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.LegalAction.PerformAndProcessResult(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.IfThenBlock.TryPerform(Law law, GameAction action, AccountChangeSet acc, LawSection section, Int32 index, LocStringBuilder sbDebug)
   at Eco.Gameplay.Civics.Laws.LawSection.CheckConditionsAndApplyEffects(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.LawSection.InternalPerform(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.LawSection.Perform(Law law, GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.Law.TryPerform(GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.Civics.Laws.LawManager.Perform(GameAction action, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(PackFlags flags, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects, AccountChangeSet acc)
   at Eco.Gameplay.GameActions.GameActionManager.GetResultWithLock(GameActionPack pack)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User userToNotify, GameActionPack actionPack)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, User userToNotify)
   at Eco.Gameplay.Placement.WorldObjectPlacementUtils.TryPlaceWorldObjectNow(Player player, WorldObjectItem item, ItemStack containingStack, Vector3i pos, Quaternion rot)
   at Eco.Gameplay.Items.WorldObjectItem.Place(Player player, Vector3i pos, Quaternion rotation)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by thomasfn** [comment]
See [0.7.2](https://github.com/thomasfn/EcoSmartTaxMod/releases/tag/0.7.2)
